### ISSUE TITLE
training code

### ISSUE THREAD

**Issue by ZhouZhang233** [zhanglichao/updatenet#1]
Hi! Lichao.
Will you publish training code?

**Comment by zhanglichao** [comment]
Hi,
We're preparing to extend it to a journal project. We will consider it later.
But we could communicate if you have questions.

/Lichao

**Comment by ZhouZhang233** [comment]
> Hi,
> We're preparing to extend it to a journal project. We will consider it later.
> But we could communicate if you have questions.
> 
> /Lichao
OK!  Thanks for your reply

**Comment by ZhouZhang233** [comment]
> Hi,
> We're preparing to extend it to a journal project. We will consider it later.
> But we could communicate if you have questions.
> 
> /Lichao

OK! Thanks for your reply
