### ISSUE TITLE
some question about the training code(in templates_generate/train_updateNet.py)

### ISSUE THREAD

**Issue by nosaydomore** [zhanglichao/updatenet#10]
hello, Thanks for your great work, I have some question for your training code(train_updateNet.py) 
对不起，我的英文是很差的，我发现您是华人好像，为了描述清楚我我用中文表述：
１．in Line 1４2 `gt = dataram['template0'][batch+gt_index-1]`  
这一行代码是读取当前batch 对应的下一帧的groudtruth处的模板，但为什么要在batch +gt_index之后减一，我的理解是batch+gt_index就是，下一帧的索引了。
２．您的产生训练数据的代码中目标 out of view 了，ground truth 是零，请问也是进行‘torch.zeros([1, 512, 6, 6], dtype=torch.float32)’来代替真实的groundtruth template吗？

**Comment by zhanglichao** [comment]
你好，

非常感谢您对我们工作感兴趣。
首先，是的，对于loss中对比的gt template, 我们选取当前帧的，这样可以理解为updatenet预测出的template即为当前帧。如果选用下一帧gt，理解为与下一帧xcorr匹配更准确。两种选取对训练效果是差不多的。

第二个问题是，我们对simulate tracking中产生的奇异值（w*h=0）,做了零填充处理。当然对于边界上的template，我们就近选取了边界值。
Hope helps you.

Thanks!

**Comment by nosaydomore** [comment]
好的，明白了，谢谢您
