### ISSUE TITLE
关于MSE损失的问题

### ISSUE THREAD

**Issue by 1878708493** [zhanglichao/updatenet#12]
您好，感谢您提供这么好的工作～
关于loss function我有一些问题，我在训练过程中MSE loss值特别大，能达到几十万，我觉得这样不正常，所以想问下您训练的时候loss值大概是多少呢？

期待回复，感谢～

**Comment by zhanglichao** [comment]
您好，
MSE是计算predicted template和real template之间的距离，如果没有normalization，结果会非常大。

谢谢

**Comment by 1878708493** [comment]
感谢您的回复！



---原始邮件---
发件人: "Lichao"<notifications@github.com&gt;
发送时间: 2019年12月3日(周二) 凌晨0:45
收件人: "zhanglichao/updatenet"<updatenet@noreply.github.com&gt;;
抄送: "1878708493"<1878708493@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [zhanglichao/updatenet] 关于MSE损失的问题 (#12)



您好，
 MSE是计算predicted template和real template之间的距离，如果没有normalization，结果会非常大。
 
谢谢
