### ISSUE TITLE
关于DaSiamRPN的代码问题

### ISSUE THREAD

**Issue by 1878708493** [zhanglichao/updatenet#14]
您好，在您的local_SiamRPN_lasot_acc.py中，有以下代码：

state = SiamRPN_init(im, target_pos, target_sz, net) 
template_acc.append(state['z_f'])
template_cur.append(state['z_f_cur'])

但是在foolwood/DaSiamRPN的代码中没有z_f和z_f_cur这两个返回值，所以我想问下您是否修改了相关代码，如果是的话方便分享下吗？十分感谢！

**Comment by zhanglichao** [comment]
hi 

The two values are used as the training templates from stimulating the real tracking, which we modify the DaSiamRPN code based on the original code. And these two values already can be got by this script.
