### ISSUE TITLE
training sequences details

### ISSUE THREAD

**Issue by de-laserre** [zhanglichao/updatenet#15]
Hi, 
Updatenet is a simple but elegant work, and your code is really helpful. 

In your paper, you mentioned that  you employed a subset containing 20 training sequences from 20 randomly selected categories, when I revisit your your code, it seems that you use a config file 'update-set1.txt' to choose your training sequences, while neither this config file nor other specifications is given in your repository.

So I was wondering could you please be more specific about training videos are you using, exactly?

**Comment by zhanglichao** [comment]
Hi,

Thanks for your interests. Yes, we were using 20 random sequences for training, and now arrange them for public later. Could you send me an email and I give you the draft version at present.

**Comment by HonglinChu** [comment]
Hi, Could you send me  the draft version at present, this is my email 1628464345@qq.com , and my weixin: chuyanqiu2255. I hope can communicate with you further

**Comment by zhu2014yi** [comment]
Hi, Could you send me the draft version at present too, this is my email jobzhuyi@gmail.com.

**Comment by zhanglichao** [comment]
hi

I've sent you emails and please check it.

**Comment by upxinxin** [comment]
Hi, Could you send me the draft version at present too, this is my email chenxinxin970717@163.com. Thank you so much!
