### ISSUE TITLE
training problems

### ISSUE THREAD

**Issue by zhu2014yi** [zhanglichao/updatenet#20]
Hi lichao!
很棒的工作，但是我有以下几点不是很清楚，希望能得到你的指导，
1. local_SiamRPN_lasot_acc.py文件里面的第48行，cx, cy, w, h = get_axis_aligned_bbox(Polygon)这个被调用的函数是输入要4个角的坐标（x1,y1,x2,y2,x3,y3,x4,y4）但是lasot的groundtruth都是（xy,w,h）类型的是否函数用错了。(这个位置我debug确实报错了)
2. local_SiamRPN_lasot_acc.py文件里面的state["z_f_cur"]是否就是SiamRPN的预测位置crop出来的模板，template_acc是否是第一帧的模板。
3. local_SiamRPN_lasot_acc.py文件里面最后保存的文件是gt.npy, init.npy, init0.npy, pre.npy, template.npy, templatei.npy(如下图)
![image](https://user-images.githubusercontent.com/42707205/74707586-313cfe00-5255-11ea-8221-b142d5280473.png)但是在训练的时候dataram["template0"]找不到（如下图）
![image](https://user-images.githubusercontent.com/42707205/74707627-444fce00-5255-11ea-802c-835ac3f29ad4.png)
望能指点一下，不甚感激！

**Comment by zhu2014yi** [comment]
补充第一张图片内容（image显示不出来）：
np.save(temp_path+'/template',template_acc)
np.save(temp_path+'/templatei',template_cur)
np.save(temp_path+'/init0',init0)
np.save(temp_path+'/init',init)
np.save(temp_path+'/pre',pre)
np.save(temp_path+'/gt',gt)
补充图片二内容（image显示不出来）：
dataram['template0'] = np.load(join(tem0_path,'template0.npy'))
dataram['template'] = np.load(join(tem_path,'template.npy'))
dataram['templatei'] = np.load(join(tem_path,'templatei.npy'))

dataram['pre'] = np.load(join(tem_path,'pre.npy'))
dataram['gt'] = np.load(join(tem_path,'gt.npy'))
dataram['init0'] = np.load(join(tem_path,'init0.npy'))
dataram['train'] = np.arange(len(dataram['gt']), dtype=np.int)

**Comment by zhanglichao** [comment]
Hi,

Thank you for your interests.
1. 我印象里这个函数是双功能的，两种类型应该都可以处理，请查看下具体函数内容可以解决；
2. ‘z_f_cur’是的，‘template_acc’为累积模板；
3. ‘template0’是每一帧用groundtruth crop出来的模板，这个应该容易获得。

谢谢。

**Comment by HonglinChu** [comment]
Hi,
    我下载了您的代码. 最近在开始训练，当我跑 local_SiamRPN_lasot_acc.py, 我发现了一些问题：
(1)

在 local_SiamRPN_lasot_acc.py的第11到13行
**修改前**
`from **net1** import SiamRPNBIG
from **run_SiamRPN1** import SiamRPN_init, SiamRPN_track
from **utils1** import get_axis_aligned_bbox,**get_axis_aligned_rect**, cxy_wh_2_rect, overlap_ratio`
，我没有在工程里面找到net1，run_siamrpn1, utils1文件 ; 最后我分别修改为和code里的net_upd， run_SiamRPN, utils 一致的名字

**修改后**
`from **net_upd** import SiamRPNBIG
from **run_SiamRPN** import SiamRPN_init, SiamRPN_track
from **utils** import get_axis_aligned_bbox,get_axis_aligned_rect, cxy_wh_2_rect, overlap_ratio`

(2)
进行完第（1）的修改之后，代码依然在第13行报错，
`line13：from **utils** import get_axis_aligned_bbox,**get_axis_aligned_rect**, cxy_wh_2_rect, overlap_ratio`
发现code/utils文件里面并没有 get_axis_aligned_rect这个函数，而生成模板函数在 第72行调用了它
，请问这个函数在哪里可以找到？DaSiamRPN的官方代码我也没有找到这个函数
`if reset:                    
                        gt_rect = **get_axis_aligned_rect**(ground_truth[frame])
                        iou = overlap_ratio(gt_rect, res)
                        if iou<=0:`

（3）
第62-64行，出现了z_f和z_f_cur ，我在code/run_SiamRPN.py里面并没有找到这两个变量，然而我在 
code/run_SiamRPN_upd.py 里面发现了z_f，但是却没有发现z_f_cur; 
`   **state** = SiamRPN_track(state, im)  # track
    #pdb.set_trace()
   template_acc.append(**state['z_f']**); template_cur.append(**state['z_f_cur']**)`

请问第12行的代码
`from run_SiamRPN1 import SiamRPN_init, SiamRPN_track`
是否应该改成
`from run_SiamRPN_upd import SiamRPN_init, SiamRPN_track`

关于训练的问题想进一步向您请教一下，希望可以加个WX: chuyanqiu2255, 感谢！

**Comment by Wanghui-Huang** [comment]
> Hi,
> 我下载了您的代码. 最近在开始训练，当我跑 local_SiamRPN_lasot_acc.py, 我发现了一些问题：
> (1)
> 
> 在 local_SiamRPN_lasot_acc.py的第11到13行
> **修改前**
> `from **net1** import SiamRPNBIG from **run_SiamRPN1** import SiamRPN_init, SiamRPN_track from **utils1** import get_axis_aligned_bbox,**get_axis_aligned_rect**, cxy_wh_2_rect, overlap_ratio`
> ，我没有在工程里面找到net1，run_siamrpn1, utils1文件 ; 最后我分别修改为和code里的net_upd， run_SiamRPN, utils 一致的名字
> 
> **修改后**
> `from **net_upd** import SiamRPNBIG from **run_SiamRPN** import SiamRPN_init, SiamRPN_track from **utils** import get_axis_aligned_bbox,get_axis_aligned_rect, cxy_wh_2_rect, overlap_ratio`
> 
> (2)
> 进行完第（1）的修改之后，代码依然在第13行报错，
> `line13：from **utils** import get_axis_aligned_bbox,**get_axis_aligned_rect**, cxy_wh_2_rect, overlap_ratio`
> 发现code/utils文件里面并没有 get_axis_aligned_rect这个函数，而生成模板函数在 第72行调用了它
> ，请问这个函数在哪里可以找到？DaSiamRPN的官方代码我也没有找到这个函数
> `if reset: gt_rect = **get_axis_aligned_rect**(ground_truth[frame]) iou = overlap_ratio(gt_rect, res) if iou<=0:`
> 
> （3）
> 第62-64行，出现了z_f和z_f_cur ，我在code/run_SiamRPN.py里面并没有找到这两个变量，然而我在
> code/run_SiamRPN_upd.py 里面发现了z_f，但是却没有发现z_f_cur;
> ` **state** = SiamRPN_track(state, im) # track #pdb.set_trace() template_acc.append(**state['z_f']**); template_cur.append(**state['z_f_cur']**)`
> 
> 请问第12行的代码
> `from run_SiamRPN1 import SiamRPN_init, SiamRPN_track`
> 是否应该改成
> `from run_SiamRPN_upd import SiamRPN_init, SiamRPN_track`
> 
> 关于训练的问题想进一步向您请教一下，希望可以加个WX: chuyanqiu2255, 感谢！

请问您的问题解决了吗，和您一样的疑惑。头疼，希望您能回复一下

**Comment by HonglinChu** [comment]
https://zhuanlan.zhihu.com/p/93891617
你可以参考上面的知乎文章，我最近一直没时间搞这个




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "huangwanghui"<notifications@github.com&gt;; 
发送时间: 2020年4月6日(星期一) 上午10:57
收件人: "zhanglichao/updatenet"<updatenet@noreply.github.com&gt;; 
抄送: "SmallLion&amp;#x1F981;&amp;#xFE0F;"<1628464345@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [zhanglichao/updatenet] training problems (#20)





  
Hi,
 我下载了您的代码. 最近在开始训练，当我跑 local_SiamRPN_lasot_acc.py, 我发现了一些问题：
 (1)
 
在 local_SiamRPN_lasot_acc.py的第11到13行
 修改前
 from **net1** import SiamRPNBIG from **run_SiamRPN1** import SiamRPN_init, SiamRPN_track from **utils1** import get_axis_aligned_bbox,**get_axis_aligned_rect**, cxy_wh_2_rect, overlap_ratio
 ，我没有在工程里面找到net1，run_siamrpn1, utils1文件 ; 最后我分别修改为和code里的net_upd， run_SiamRPN, utils 一致的名字
 
修改后
 from **net_upd** import SiamRPNBIG from **run_SiamRPN** import SiamRPN_init, SiamRPN_track from **utils** import get_axis_aligned_bbox,get_axis_aligned_rect, cxy_wh_2_rect, overlap_ratio
 
(2)
 进行完第（1）的修改之后，代码依然在第13行报错，
 line13：from **utils** import get_axis_aligned_bbox,**get_axis_aligned_rect**, cxy_wh_2_rect, overlap_ratio
 发现code/utils文件里面并没有 get_axis_aligned_rect这个函数，而生成模板函数在 第72行调用了它
 ，请问这个函数在哪里可以找到？DaSiamRPN的官方代码我也没有找到这个函数
 if reset: gt_rect = **get_axis_aligned_rect**(ground_truth[frame]) iou = overlap_ratio(gt_rect, res) if iou<=0:
 
（3）
 第62-64行，出现了z_f和z_f_cur ，我在code/run_SiamRPN.py里面并没有找到这两个变量，然而我在
 code/run_SiamRPN_upd.py 里面发现了z_f，但是却没有发现z_f_cur;
  **state** = SiamRPN_track(state, im) # track #pdb.set_trace() template_acc.append(**state['z_f']**); template_cur.append(**state['z_f_cur']**)
 
请问第12行的代码
 from run_SiamRPN1 import SiamRPN_init, SiamRPN_track
 是否应该改成
 from run_SiamRPN_upd import SiamRPN_init, SiamRPN_track
 
关于训练的问题想进一步向您请教一下，希望可以加个WX: chuyanqiu2255, 感谢！
  
请问您的问题解决了吗，和您一样的疑惑。头疼，希望您能回复一下
